site:
  name: # å·¦ä¸Šè§’æ˜¾ç¤ºå†…å®¹
    class: i_class #i_class/text/img
    custom: sco-logo #è‡ªå®šä¹‰å†…å®¹ ä¾‹å¦‚ï¼šsco-logo / ç‹å“Sco / https://p.sondy.top/logo.png
  siteIcon: https://p.wzsco.top/c2013363b90760e09472680c64b0c516.png/cover.240w # ç½‘é¡µicon
  icon: https://p.wzsco.top/c2013363b90760e09472680c64b0c516.png/cover.240w # ç½‘é¡µicon

nav:
  left:
    enable: true
    menu:
      æˆ‘çš„:
        ä¸»é¡µ:
          icon: https://p.wzsco.top/97b503a253f6611157d0fbab92b3847e.png/cover.mini
          url: https://wzsco.top/
        åšå®¢:
          icon: https://p.wzsco.top/97b503a253f6611157d0fbab92b3847e.png/cover.mini
          url: /
      é¡¹ç›®:
        Solitude:
          icon: https://p.wzsco.top/fee3ff021aa27a3f68b5e7c8a8e05282.webp/cover.mini
          url: https://github.com/wleelw/Hexo-Theme-solitude
        Liu:
          icon: https://p.wzsco.top//75454e1e59d8fa347e15a5aaaceaf42b.png/cover.mini
          url: https://github.com/wleelw/hexo-theme-liu
        img2color:
          icon: https://p.wzsco.top//586f2a864052a2f5b2b7c3c37e6453e6.png/cover.mini
          url: https://github.com/wleelw/img2color
        ScoGPT:
          icon: https://p.wzsco.top//0ba4e935d8dbf28a464d4843c9ea0680.png/cover.mini
          url: https://github.com/wleelw/Post-Summary-AI
      å†…ç½®å·¥å…·:
        ç½‘ç«™ç¼©ç•¥å›¾:
          icon: https://p.wzsco.top/3a239fc09f16a239d8367ec748dc2b25.png/cover.mini
          url: /thumbnail/

  menu:
    æ–‡åº“:
      url: false
      child:
        æ–‡ç« åˆ—è¡¨:
          url: /archives/
          icon: sco-folder-fill
        å…¨éƒ¨åˆ†ç±»:
          url: /categories/
          icon: sco-checkbox-multiple-blank-fill
        å…¨éƒ¨æ ‡ç­¾:
          url: /tags/
          icon: sco-price-tag-fill
    å‹é“¾:
      url: false
      child:
        å‹é“¾é±¼å¡˜:
          url: /moments/
          icon: sco-wifi-fill
        å‹æƒ…é“¾æ¥:
          url: /links/
          icon: sco-group-fill
        å®è—åšä¸»:
          url: javascript:travelling()
          icon: sco-gift-fill
    æˆ‘çš„:
      url: false
      child:
        ç›¸å†Œé›†:
          url: /gallery/
          icon: sco-image-fill
        è£…å¤‡:
          url: /equipment/
          icon: sco-laptop-line
        å·¥å…·ç®±:
          url: /tlink/
          icon: sco-tools-fill
        éŸ³ä¹é¦†:
          url: /music/
          icon: sco-disc-fill
    å…³äº:
      url: false
      child:
        å…³äºæœ¬ç«™:
          url: /about/
          icon: sco-contacts-fill

  right:
    random: true        # éšæœºæ–‡ç« è·³è½¬
    console: true       #æ§åˆ¶å°
    # ä»å·¦è‡³å³
    custom:
      - name: å¼€å¾€ - å‹é“¾æ¥åŠ›
        url: https://www.travellings.cn/go.html
        icon: sco-train-line
        onclick:
        id: travellings_button
      - name: è™«æ´ - å‹é“¾æ¥åŠ›
        url: https://foreverblog.cn/go.html
        icon : sco-forever-solid
        onclick:
        id: travellings_button

hometop:
  banner:
    enable: true # æ˜¯å¦æ‰“å¼€é¡¶éƒ¨banner
    title: å®é™è‡´è¿œ<br>çƒ­çˆ±ç”Ÿæ´» # å·¦ä¸Šè§’æ˜¾ç¤ºæ–‡å­—
    url: WWW.WZSCO.CN # titleä¸‹æ–¹å°å­—
    icon:
      HTML:
        img: https://p.wzsco.top/ef972289c5bf712eefe72a2f143f095b.png/cover
        color: '#e9572b'
      JS:
        img: https://p.wzsco.top/93748c292ca517fc5d84c848a028fde6.png/cover
        color: '#f7cb4f'
      CSS3:
        img: https://p.wzsco.top/a5ec1ea015a37fa6e69d649d24971a5f.webp/cover
        color: '#2965f1'
      Kotlin:
        img: https://p.wzsco.top/b5fde63e4da03ba9cc3138c04130dd5d.png/cover
        color: '#ffffff'
      Docker:
        img: https://p.wzsco.top/a40ed7ba88df173ca610a9e29559eb4e.png/cover
        color: '#57b6e6'
      WebPack:
        img: https://p.wzsco.top/6b369fe516eb325383818cb6513ea24b.png/cover
        color: '#2e3a41'
      Git:
        img: https://p.wzsco.top/e9af1b021e98ac24bddf4de3259aea34.png/cover
        color: '#df5b40'
      VS:
        img: https://p.wzsco.top/658d37bcce45e8a430d05f2de4234dc2.png/cover
        color: '#ffffff'

  categoryGroup:
    G1:
      name: å¿…çœ‹ç²¾é€‰
      icon: sco-star-smile-fill
      url: /tags/ç²¾é€‰/
    G2:
      name: çƒ­é—¨æ–‡ç« 
      icon: sco-fire-fill
      url: /tags/çƒ­é—¨/
    G3:
      name: å®ç”¨æ•™ç¨‹
      icon: sco-book-mark-fill
      url: /tags/æ•™ç¨‹/

  recommendList:
    sup: ç½®é¡¶ # å·¦ä¸Šè§’æ˜¾ç¤ºæ–‡å­—
    title: Solitudeä¸»é¢˜æ–‡æ¡£ # å·¦ä¸‹è§’å¤§å­—
    url: https://solitude.wzsco.cn/posts/a0e4c699.html # ç‚¹å‡»è·³è½¬é“¾æ¥
    img: https://p.wzsco.top//d05332998b3404477cbc4e256ec80d79.png/cover # æ˜¾ç¤ºèƒŒæ™¯
    color: '#006a73' # èƒŒæ™¯é¢œè‰²

aside:
  # å€¼ï¼šaboutï¼ˆå…³äºæˆ‘ï¼‰ã€newestPostï¼ˆæœ€æ–°æ–‡ç« ï¼‰ã€allInfoï¼ˆç½‘ç«™ä¿¡æ¯ï¼‰ã€flipï¼ˆå…¬ä¼—å·äºŒç»´ç ï¼‰
  home: # åœ¨ä¸»é¡µæ˜¾ç¤ºçš„ä¾§è¾¹æ ä¿¡æ¯
    noSticky: "about"
    Sticky: "flip,allInfo"
  post: # åœ¨æ–‡ç« é¡µæ˜¾ç¤ºçš„ä¾§è¾¹æ ä¿¡æ¯
    noSticky: "about"
    Sticky: "newestPost"
  page: # åœ¨é¡µé¢ä¸­æ˜¾ç¤ºçš„ä¾§è¾¹æ ä¿¡æ¯
    noSticky: "about"
    Sticky: "newestPost,allInfo"
  card:
    author:
      img: https://p.wzsco.top/7c83eaa868cc25b6ed76d6b299fd9f53.webp/cover.240w # å¤´åƒ
      sticker: https://bu.dusays.com/2023/12/30/659011053e246.png # è´´çº¸
    content: åˆ†äº«è‡ªå·±å¯¹ç¼–ç¨‹çš„<b>çƒ­çˆ±</b>ï¼Œå¯¹ç¾å¥½ç”Ÿæ´»çš„<b>å‘å¾€</b>ï¼Œå¯¹çŸ¥è¯†æµ·æ´‹<b>æ¢ç´¢å†ç¨‹</b>ã€‚ # æ–‡æ¡ˆ1
    content2: ç›¸ä¿¡ä½ å¯ä»¥åœ¨è¿™é‡Œæ‰¾åˆ°å¯¹ä½ æœ‰ç”¨çš„çŸ¥è¯†å’Œæ•™ç¨‹ã€‚ # æ–‡æ¡ˆ2
    sayhello:
      morning: ä¸€æ—¥ä¹‹è®¡åœ¨äºæ™¨
      noon: åƒé¥±äº†æ‰æœ‰åŠ›æ°”å¹²æ´»
      afternoon: é›†ä¸­ç²¾åŠ›ï¼Œæ”»å…‹éš¾å…³
      night: ä¸è¦å¤ªåŠ³ç´¯äº†ï¼Œæ—©ç¡æ›´å¥åº·
      goodnight: ç¡ä¸ªå¥½è§‰ï¼Œä¿è¯ç²¾åŠ›å……æ²›
    sayhello2:
      - ğŸ¤–ï¸ æ•°ç ç§‘æŠ€çˆ±å¥½è€…
      - ğŸ” åˆ†äº«ä¸çƒ­å¿ƒå¸®åŠ©
      - ğŸ  æ™ºèƒ½å®¶å±…å°èƒ½æ‰‹
      - ğŸ”¨ è®¾è®¡å¼€å‘ä¸€æ¡é¾™
      - ğŸ¤ ä¸“ä¿®äº¤äº’ä¸è®¾è®¡
      - ğŸƒ è„šè¸å®åœ°è¡ŒåŠ¨æ´¾
      - ğŸ§± å›¢é˜Ÿå°ç»„å‘åŠ¨æœº
      - ğŸ’¢ å£®æ±‰äººç‹ è¯ä¸å¤š
      - ğŸ® ç”µç«æ¸¸æˆçˆ±å¥½è€…
    information:
      Github:
        icon: sco-github-line
        url: https://github.com/wleelw
      Bilibili:
        icon: sco-bilibili-line
        url: https://space.bilibili.com/1329819902

  flip:
    favicon: "https://p.wzsco.top/10c0aa0d7da5c06728bbb59376755184.png/cover" # å³ä¸‹è§’å¤´åƒ
    face: "https://p.wzsco.top/d420ce76c0365e86d052f9d09004f26e.webp/cover" # æ­£é¢
    backface: "https://p.wzsco.top/070573da14a225f10a38dc21aea3cc21.webp/cover" # é¼ æ ‡æ‚¬åœç¿»è½¬å›¾ç‰‡

  toc:
    post: true # åœ¨æ–‡ç« é¡µæ˜¾ç¤º
    page: false # åœ¨ä»»æ„é¡µæ˜¾ç¤º

  tags:
    enable: true # æ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    limit: 20 # æ˜¾ç¤ºæ ‡ç­¾æ•°é‡ï¼Œå½“é«˜äºæ ‡ç­¾æ€»æ•°æ—¶ï¼Œæ˜¾ç¤ºå…¨éƒ¨æ ‡ç­¾æŒ‰é’®
    highlight: true # é«˜äº®æ˜¾ç¤º
    list: # é«˜äº®æ˜¾ç¤ºæ ‡ç­¾åˆ—è¡¨
      - 'Solitude'
      - 'img2color'
      - 'ScoGPT'
      - 'æ•™ç¨‹'
      - 'çƒ­é—¨'

  archive:
    enable: false # æ˜¯å¦æ˜¾ç¤ºå½’æ¡£
    type: 'month' # monthly: æŒ‰æœˆ / yearly: æŒ‰å¹´

  siteinfo:
    postcount: true # æ–‡ç« æ•°
    wordcount: true # æ€»å­—æ•°
    pv: true # è®¿é—®é‡
    uv: false # è®¿å®¢æ•°
    updatetime: true # æœ€åæ›´æ–°æ—¥æœŸ
    runtimeenable: true # å»ºç«™æ—¶é—´
    runtime: '2023-04-20 00:00:00' # æ ¼å¼ï¼šyyyy-MM-dd hh-mm-ss

footer:
  information:
    left: # å·¦ä¾§æ˜¾ç¤ºå›¾æ ‡
      Github:
        icon: sco-github-line
        url: https://github.com/wleelw
      Mail:
        icon: sco-mail-line
        url: mailto:wleelw@wzsco.top
    right: # å³ä¾§æ˜¾ç¤ºå›¾æ ‡
      Bilibili:
        icon: sco-bilibili-line
        url: https://space.bilibili.com/1329819902
      æŠ–éŸ³:
        icon: sco-douyin-fill
        url: https://v.douyin.com/iJsLc8jt/
  group: # ä»å·¦è‡³å³
    å¯¼èˆª:
      å½’æ¡£: /archives/
      åˆ†ç±»: /categories/
      æ ‡ç­¾: /tags/
    ä¸»é¢˜:
      æ–‡æ¡£: https://docs.wzsco.cn/
      æºç : https://github.com/wleelw/Hexo-theme-solitude
      æ›´æ–°æ—¥å¿—: /update/
    æœåŠ¡:
      é˜¿é‡Œäº‘: https://aliyun.com/
      51laç»Ÿè®¡: https://v6.51.la/
      ç™¾åº¦ç»Ÿè®¡: https://tongji.baidu.com/
    æ”¯æŒ:
      æ‰“èµè®°å½•: /about/
    åè®®:
      Cookies: /cookies/
      éšç§æ”¿ç­–: /privacy/
      ç‰ˆæƒåè®®: /cc/

  randomlink: true
  privacy: /privacy/
  license: /cc/
  links:
    # ä¸ºäº†ä¸»é¢˜èƒ½å¤Ÿå¾—åˆ°æ›´å¤šçš„æ”¯æŒï¼Œå»ºè®®ä¿ç•™ä¸»é¢˜é“¾æ¥
    # In order for the theme to get more support, it is recommended to keep the theme link
    - name: ä¸»é¢˜
      url: https://github.com/wleelw/hexo-theme-solitude
    - name: è®¢é˜…
      url: /atom.xml

page:
  error: true #
  tags: true # æ ‡ç­¾
  categories: true # åˆ†ç±»
  default: # é»˜è®¤å€¼
    cover:
      - /img/default.png # é»˜è®¤å›¾ç‰‡
      - https://p.wzsco.top/e5b22e531c7f2717d7c909bb912eb34a.webp/cover

post:
  default:
    cover:
      - /img/default.png # é»˜è®¤å›¾ç‰‡
      - https://p.wzsco.top/e5b22e531c7f2717d7c909bb912eb34a.webp/cover
    locate: è¡¡é˜³
    copyright:
      enable: true
      license: CC BY-NC-SA 4.0
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
      author:
        enable: false
        author_back: https://bu.dusays.com/2023/11/01/6541f6d4b2573.png # åº•éƒ¨å¤´åƒèƒŒæ™¯
  meta:
    date: true # å‘å¸ƒæ—¥æœŸ
    updated: true # æ›´æ–°æ—¥æœŸ
    locate: true # ä½ç½®
    wordcount: true # å­—æ•°
    readtime: true # è®¿é—®
    pv: true # æµè§ˆé‡
    comment: true # è¯„è®ºæ•°
  award:
    enable: true # å¼€å¯åæ–‡ç« åº•éƒ¨æ˜¾ç¤ºæ‰“èµæŒ‰é’®
    wechat: https://bu.dusays.com/2023/11/07/6549e79364fa3.png
    alipay: https://bu.dusays.com/2023/11/07/6549e79d02bd6.png
    url: /about # æ‰“èµç»Ÿè®¡é¡µé¢é“¾æ¥
  rss: /atom.xml
  # æ–‡ç« é¢œè‰²è·å–
  covercolor: #æ–‡ç« coverå–è‰²
    enable: true # æ˜¯å¦å¼€å¯
    mode: api #localï¼šæœ¬åœ°å–è‰² / apiï¼šimg2colorå–è‰²
    api: https://img2color.wzsco.top/api?img=
    time: 43200000 # apiå–è‰²é—´éš”ï¼ˆæ¯«ç§’ï¼‰ï¼Œé»˜è®¤ä¸º12å°æ—¶

keyboard:
  enable: true
  list:
    - name: å…³é—­å¿«æ·é”®åŠŸèƒ½
      key: K
      sco: switchKeyboard
    - name: æ‰“å¼€ä¸­æ§å°
      key: A
      sco: showConsole
    - name: æ’­æ”¾/æš‚åœéŸ³ä¹
      key: M
      sco: musicToggle
    - name: æ·±è‰²/æµ…è‰²æ¨¡å¼åˆ‡æ¢
      key: N
      sco: switchDarkMode
    - name: ç«™å†…æœç´¢
      key: S
      func: openSearch
    - name: éšæœºè®¿é—®
      key: R
      func: toRandomPost
    - name: è¿”å›é¦–é¡µ
      key: H
      url: /
    - name: å‹æƒ…é“¾æ¥
      key: L
      url: '/links/'
    - name: å…³äºæœ¬ç«™
      key: P
      url: '/about/'

meting_api: "https://meting.qjqq.cn/?server=:server&type=:type&id=:id&auth=:auth&r=:r" #è‡ªå®šä¹‰api

music:
  enable: true # æ˜¯å¦å¼€å¯
  id: 8407304077 # æ­Œå•id
  server: netease # æ’­æ”¾åˆ—è¡¨çš„æœåŠ¡å•†ã€‚neteaseï¼šç½‘æ˜“äº‘ / tencentï¼šè…¾è®¯ / kugouï¼šé…·ç‹— / xiamiï¼šå°ç±³ / baiduï¼šç™¾åº¦
  type: playlist # æ’­æ”¾åˆ—è¡¨çš„ç±»å‹ã€‚songï¼šå•æ›² / playlistï¼šæ­Œå• / albumï¼šä¸“è¾‘ / artistï¼šæ­Œæ‰‹
  volume: 0.8 # åˆå§‹éŸ³é‡ã€‚0.8 = 80%ï¼ŒèŒƒå›´ 0 åˆ° 1
  mutex: true # æ˜¯å¦å¼€å¯äº’æ–¥æ¨¡å¼ï¼Œå³åŒæ—¶åªèƒ½æœ‰ä¸€ä¸ªæ’­æ”¾å™¨æ’­æ”¾

capsule:
  enable: true
  id: 8407304077 # æ­Œå•id
  server: netease # æ’­æ”¾åˆ—è¡¨çš„æœåŠ¡å•†ã€‚neteaseï¼šç½‘æ˜“äº‘ / tencentï¼šè…¾è®¯ / kugouï¼šé…·ç‹— / xiamiï¼šå°ç±³ / baiduï¼šç™¾åº¦
  type: playlist # æ’­æ”¾åˆ—è¡¨çš„ç±»å‹ã€‚songï¼šå•æ›² / playlistï¼šæ­Œå• / albumï¼šä¸“è¾‘ / artistï¼šæ­Œæ‰‹

moments:
  enable: true # æ˜¯å¦å¼€å¯é±¼å¡˜ / Whether to enable fish pond
  api: https://moments.wzsco.top/ # apiåœ°å€ / api address
  error_img: https://bu.dusays.com/2023/11/08/654af68b25bb8.jpg # åŠ è½½å¤±è´¥æ˜¾ç¤ºå›¾ç‰‡ / Loading failed display image
  sort_rule: created # æ’åºè§„åˆ™ï¼šcreatedï¼šæŒ‰åˆ›å»ºæ—¶é—´æ’åº / updatedï¼šæŒ‰æ›´æ–°æ—¶é—´æ’åº : Sort rule: created: Sort by creation time / updated: Sort by update time
  expire_days: 1 # ç¼“å­˜è¿‡æœŸæ—¶é—´ï¼ˆå¤©ï¼‰ï¼Œé»˜è®¤ä¸º1å¤© / Cache expiration time (days), default is 1 day
  page_init_number: 10 # é¡µé¢åˆå§‹åŒ–åŠ è½½æ•°é‡ï¼Œé»˜è®¤ä¸º10æ¡ / Page initialization loading quantity, default is 10
  page_turning_number: 5 # é¡µé¢ç¿»é¡µåŠ è½½æ•°é‡ï¼Œé»˜è®¤ä¸º5æ¡ / Page turning loading quantity, default is 5
  angle: true # é±¼å¡˜éšæœºæ–‡ç«  / Fish pond random article
  appjs: https://cdn.cbd.int/solitude-source@1.0.3/js/fcircle.min.js # é±¼å¡˜js / Fish pond js
  bundlejs: https://cdn.cbd.int/solitude-source/js/moment/bundle.min.js # é±¼å¡˜js / Fish pond js
  randompostjs: https://cdn.cbd.int/solitude-source/js/moment/random_post.min.js # é±¼å¡˜js / Fish pond js

errorpage:
  img: https://p.wzsco.top//42d6f1ea88d53c76ea2df0c520356a68.png/cover
  text: è¯·å°è¯•ç«™å†…æœç´¢å¯»æ‰¾æ–‡ç« 
  recommendList: true # æ˜¾ç¤ºéšæœºæ–‡ç« 

lazyload:
  enable: true
  placeholder: /img/loading.gif # åŠ è½½ä¸­æ˜¾ç¤ºå›¾ç‰‡
  errorimg: /img/error_load.png # åŠ è½½å¤±è´¥æ˜¾ç¤ºå›¾ç‰‡

lightbox: true

# fancybox
# https://fancyapps.com/fancybox/
fancybox: true

# mediumZoom
mediumZoom: false

hightlight:
  enable: true
  hightlimit: 200
  copy: true # æ˜¯å¦å¼€å¯å¤åˆ¶æŒ‰é’®
  expand: true # æ˜¯å¦é»˜è®¤å±•å¼€
  # ä»£ç å—æ ·å¼
  theme: mac # default: é»˜è®¤ / mac
  color: vscode # default: é»˜è®¤  / vscode / solarized-dark / solarized-light / dracula / monokai

loading:
  fullpage: true
  pace: true

wordcount: false
# è®¿é—®ç»Ÿè®¡
busuanzi: true

search:
  enable: true
  # algolia, local
  type: algolia
  tags:
    - 'ç²¾é€‰'
    - 'Hexo'
  algolia:
    hits:
      per_page: 6
  local:
    preload: false
    CDN:

album:
  enable: true # æ˜¯å¦å¼€å¯ç›¸å†Œ / Whether to enable album
  limit: 6 # å•è¡Œæ˜¾ç¤ºå›¾ç‰‡æ•°é‡ / Number of pictures displayed in a single line

# æ–‡ç« é¡µé¢AI
post_ai:
  enable: true # æ˜¯å¦å¼€å¯
  # å³ä¾§æ˜¾ç¤ºçš„æ¨¡å‹åç§°
  modelName: ScoGPT
  # key
  # å…·ä½“è·å–æ–¹æ³•è§æ–‡æ¡£
  key: "Qi7QIXLOrxLCyKBW0bie"
  # è‡ªä»‹
  talk: æˆ‘æ˜¯ç‹å“Scoå¼€å‘çš„æ‘˜è¦ç”ŸæˆåŠ©ç†ScoGPTï¼ŒScoGPTåœ¨é™æ€éƒ¨ç½²æ—¶è¿›è¡Œæ‘˜è¦çš„æ’°å†™ï¼Œå¹¶ä¸”åœ¨è®¿å®¢è®¿é—®æ—¶é€šè¿‡ScoCorrectionè½¬è¯‘åçš„æ–‡æœ¬æ‘˜è¦å®ç°å·¥å…·ã€‚æˆ‘åœ¨è¿™é‡Œåªè´Ÿè´£å·²ç»ç”Ÿæˆçš„æ‘˜è¦æ˜¾ç¤ºï¼Œä½ æ— æ³•ä¸æˆ‘ç›´æ¥æ²Ÿé€šï¼Œä½†æˆ‘å¯ä»¥å›ç­”ä¸€äº›é¢„è®¾çš„é—®é¢˜ã€‚
  # éšæœºæ–‡ç« æŒ‰é’®
  randomPost: false
  # ä¸¾æŠ¥é“¾æ¥ï¼Œä¸å¡«ä¸æ˜¾ç¤º
  report: /about/
  # åº•éƒ¨æç¤º
  tips: æ­¤å†…å®¹æ ¹æ®æ–‡ç« ç”Ÿæˆï¼Œå¹¶ç»è¿‡äººå·¥å®¡æ ¸ï¼Œä»…ç”¨äºæ–‡ç« å†…å®¹çš„è§£é‡Šä¸æ€»ç»“

comment:
  enable: true
  type: waline # waline, twikoo
  commentBarrage: true # çƒ­è¯„å¼€å…³
  newComment: true # æœ€æ–°è¯„è®ºå¼€å…³
  twikoo:
    envId: https://twikoo.wzsco.cn/.netlify/functions/twikoo
    lang: 'zh-CN'
    accessToken:  # accessToken
  waline: # https://waline.js.org/
    envId: https://waline-netlify.netlify.app/.netlify/functions/comment  # url: https://waline.wzsco.top
    pageview: false # æ˜¯å¦å¼€å¯é¡µé¢è®¿é—®é‡ç»Ÿè®¡ / Whether to enable page access statistics
    option: # walineé…ç½®é¡¹ / waline configuration item

extends:
  head: # åœ¨headä¸­æ’å…¥
    - <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js"></script>
    - <script>LA.init({id:"3F15j2vtdTo7PPcN",ck:"3F15j2vtdTo7PPcN"})</script>
    - <script>
      var _hmt = _hmt || [];
      (function() {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?f17c3dd0c43cecfef2f02ae5e7dc00d7";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
      })();
      </script>
  body: # åœ¨bodyä¸­æ’å…¥
  # è‡ªå®šä¹‰jså¿…é¡»æ”¾åˆ°è¿™ä¸¤ä¸ªä¸‹é¢ï¼Œå¦‚ï¼š

related_post:
  enable: true
  limit: 2 # æ¨èæ–‡ç« æ•°é‡
  date_type: created # æ ¹æ®åˆ›å»ºæ—¥æœŸï¼ˆcreatedï¼‰æˆ–æ˜¯æ›´æ–°æ—¥æœŸï¼ˆupdatedï¼‰

translate:
  enable: true
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  defaultEncoding: 2
  # Time delay
  translateDelay: 0

katex:
  enable: true # æ˜¯å¦å¼€å¯
  per_page: true # æ˜¯å¦åœ¨æ¯é¡µéƒ½åŠ è½½
  copytex: true # æ˜¯å¦å¼€å¯å¤åˆ¶å…¬å¼

rightside:
  enable: true

verify_site:
  # ç™¾åº¦
  - name: baidu-site-verification
    content: codeva-KReTIJu5us
  # 360
  - name: 360-site-verification
    content: 512b9344e1978ea8ef2363d7d9478625
  # bing
  - name: msvalidate.01
    content: 7EBDEFFBCC9B2A2F2DCC7A53B7B02D02
pwa:
  enable: true
  manifest: /manifest.json
  theme_color: '#ffffff'
  mask_icon: https://p.wzsco.top/pwa/192.png/cover
  apple_touch_icon: https://p.wzsco.top/pwa/192.png/cover
  bookmark_icon: https://p.wzsco.top/pwa/192.png/cover
  favicon_32_32: https://p.wzsco.top/pwa/32.png/cover
  favicon_16_16: https://p.wzsco.top/pwa/16.png/cover

says:
  enable: true
  home_mini: true
  style: 1
  strip: 30

opengraph:
  enable: true
  options:
  # twitter_card:
  # twitter_image:
  # twitter_id:
  # twitter_site:
  # google_plus:
  # fb_admins:
  # fb_app_id:

css_prefix: false

CDN:
  # æœ¬åœ°æ–‡ä»¶ CDN ï¼š source/js/*.js
  internal: custom
  third_party: custom
  version: true
  custom_format: https://cdn.staticfile.org/${cdnjs_name}/${version}/${min_cdnjs_file}
#  custom_format: https://cdn.bootcdn.net/ajax/libs/${cdnjs_name}/${version}/${min_cdnjs_file}
  option:
    scoicon_css: https://cdn2.codesign.qq.com/icons/7pOrz0WXB5ZWJPX/latest/iconfont.css